[package]
name = "ArgentumCoopBevy"
version = "0.1.0"
edition = "2024"

[dependencies]

bevy = { version = "0.16.1", features = ["dynamic_linking", "track_location"] }
bevy_ecs_tilemap = "0.16.0"
bevy_renet = "1.0.0"

bevy_simple_scroll_view = "0.4.0"
bevy_ui_text_input = "0.5.2"
nano-id = "0.4.0"
rand = "0.9.1"
strum = "0.27.1"
strum_macros = "0.27.1"
superstate = { git = "https://github.com/KurlykovDanila/Superstate.git" }

[dependencies.fastnoise-lite]
version = "*"
features = ["f64"]

#log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] } # Improve Runtime Performance (Optional) 

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3



bincode = "1.3-1"
