[package]
name = "camera"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../acommon" }
game_common = { path = "../agame_common" }
dimension_shared = { path = "../dimension_shared" }
sprite = { path = "../sprite" }

bevy = { workspace = true }