[target.x86_64-pc-windows-msvc]
 # Use LLD Linker
rustflags = [
  "-Zshare-generics=off", # (Nightly)
  "-Zthreads=0",        # (Nightly) Use improved multithreading with the recommended amount of threads.
]